---
- hosts: frontend
  tasks:
    - name: Barnacle the frontend
      import_role:
        name: barnacle

    - name: Reboot the frontend
      shell: sleep 2 && shutdown -r now
      async: 1
      poll: 0
      ignore_errors: true

    - name: Wait for the frontend to boot
      wait_for_connection:
        delay: 30
        timeout: 300

    - name: Re-mount the cache folder
      command: mount -t vboxsf export_isos /export/isos
      args:
        warn: false
    
    - name: Re-mount the tests folder
      command: mount -t vboxsf export_tests /export/tests
      args:
        warn: false
    
    - name: Set up the OS pallet
      import_role:
        name: os-pallet

    - name: Set up the Vagrant cart
      import_role:
        name: vagrant-cart
